FROM alpine:latest

RUN apk add --update nodejs npm libpq-dev gdal gdal-tools gdal-driver-PG
RUN npm install --global yarn
RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app
VOLUME /usr/src/app

ENV PORT=80
ENV GDAL=local
ENV CRON=@daily

EXPOSE 80

CMD yarn scripts:municipios & yarn scripts:queimadas --cron $CRON & yarn install && yarn dev
